version: "2"
linters:
  default: standard
  exclusions:
      rules:
        - text: "^unused-parameter:"
          linters: [revive]
        - text: "^exported:"
          linters: [revive]
          path: braintrust/internal
        - text: "package-comments:"
          linters: [revive]
          path: braintrust/internal
        - text: "package-comments:"
          linters: [revive]
          path: examples/
        - text: "SA1019:"
          linters: [staticcheck]



  enable:
    - bodyclose
    - forcetypeassert # catches potential panics
    - usetesting      # nice-to-have not critical
    - thelper         # nice-to-have not critical
    - revive          # critical for ensuring public functions/packages have docs.


formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/braintrustdata/braintrust-x-go
