version: "2"
linters:
  default: standard
  exclusions:
      rules:
        - text: "^unused-parameter:"
          linters: [revive]
        - text: "^exported:"
          linters: [revive]
          path: braintrust/internal
        - text: "package-comments:"
          linters: [revive]
          path: braintrust/internal

  enable:
    - bodyclose
    - usetesting
    - thelper
    - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/braintrust/braintrust-x-go
