version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - usetesting

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/braintrust/braintrust-x-go
