name: CI

on:
  push:
    branches: [ main ]  # This runs on pushes/merges to main
  pull_request:  # This runs on all pull requests

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest]
    env:
      CGO_ENABLED: 0
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY}}
      BRAINTRUST_API_KEY: ${{ secrets.BRAINTRUST_API_KEY}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

      - name: Lint, vet, tests, etc.
        run: make ci

      - name: Generate coverage report
        if: success()
        run: make cover
