name: CI

on:
  push:
    branches: [ main ]  # This runs on pushes/merges to main
  pull_request:  # This runs on all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          args: --timeout=5m
          install-mode: binary

      - name: Lint, vet, tests, etc.
        run: just ci

      - name: Generate coverage report
        if: success()
        run: just cover

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 7
