name: CI

on:
  push:
    branches: [ main ]  # This runs on pushes/merges to main
  pull_request:  # This runs on all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22", "1.23", "1.24", "1.25"]
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY}}
      BRAINTRUST_API_KEY: ${{ secrets.BRAINTRUST_API_KEY}}
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true # install tools from mise.toml
      - name: Setup Go ${{ matrix.go }}
        run: |
          mise install go@${{ matrix.go }}
          mise use go@${{ matrix.go }}
          go version

      - name: Lint, vet, tests, etc.
        run: make ci

      - name: Generate coverage report
        if: success()
        run: make cover

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report-go-${{ matrix.go }}
          path: coverage.html
          retention-days: 7
